services:
  # Auth service
  auth-service:
    build:
      context: .  # Use root directory as build context
      dockerfile: Dockerfile.auth
    environment:
      - DB_HOST=${DB_HOST:-host.docker.internal} # DNS that resolves to host machine
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres} # DO NOT USE IN PRODUCTION
      - DB_NAME=${DB_NAME:-auth_db}
      - SERVER_HOST=0.0.0.0  # All interfaces
      - SERVER_PORT=50051
      - GRAPH_HOST=graph-service
      - GRAPH_PORT=50052
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux requires this for DNS resolution?

  # Graph service
  graph-service:
    build:
      context: .
      dockerfile: Dockerfile.graph
    environment:
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres} # DO NOT USE IN PRODUCTION
      - DB_NAME=${DB_NAME:-graph_db}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=50052
      - AUTH_HOST=auth-service
      - AUTH_PORT=50051
    ports:
      - "50052:50052"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50052"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    extra_hosts:
      - "host.docker.internal:host-gateway"
