# Graph Service Configuration Example

# Common configuration
environment: "development" # Controls environment-specific behaviors
                           # Options: "development" | "production"
                           # - development: Enables debugging features, detailed logging
                           # - production: Optimizes for performance, minimal logging
                           # Default: "production"

# Server configuration
server:
  # Main gRPC server settings
  host: "localhost"    # The IP address or hostname the server will listen on
                       # Default: "localhost"
  port: 50052          # The port number for the gRPC server
                       # Valid range: 1-65535
                       # Default: 50052 (Note: Different from auth service default)
  
  # Prometheus metrics server settings
  metrics:
    host: "localhost"  # Host address for the metrics server
                       # Default: "localhost"
    port: 2112         # Port for exposing Prometheus metrics
                       # Valid range: 1-65535
                       # Default: 2112
    path: "/metrics"   # HTTP endpoint path for metrics
                       # Default: "/metrics"

# Database configuration (PostgreSQL)
database:
  host: "localhost"          # Database server hostname
                             # Default: "localhost"
  port: 5432                 # Database server port
                             # Default: 5432
  user: "postgres"           # Database user name
                             # Default: "postgres"
  password: "your_password"  # Database password
                             # Default: "" (empty)
  dbname: "graph_db"         # Name of the database to connect to
                             # Default: "graph_db" (Note: Different from auth service default)

  # Connection pool settings
  max_open_conns: 10              # Maximum number of open connections to the database
                                  # Higher values allow more concurrent operations
                                  # Default: 10
  max_idle_conns: 5               # Maximum number of idle connections in the pool
                                  # Should be less than max_open_conns
                                  # Default: 5
  conn_max_lifetime: "5m"         # Maximum time a connection can be reused
                                  # Format: Go duration string (e.g., "5m", "1h")
                                  # Default: "5m"

  # Development settings
  drop_tables: false              # If true, drops and recreates all tables on startup
                                  # WARNING: Never enable in production!
                                  # Default: false

# Logger configuration (using zap)
logger:
  environment: "development"    # Logging configuration preset
                                # Options: "development" | "production"
                                # - development: Colored output, readable format
                                # - production: JSON format, optimized for parsing
                                # Default: "development"
  level: "debug"                # Minimum log level to output
                                # Options: "debug" | "info" | "warning" | "error"
                                # Each level includes all higher levels
                                # Default: "debug"
  encoding: "console"           # Log output format
                                # Options: "json" | "console"
                                # - console: Human-readable format
                                # - json: Machine-parseable JSON
                                # Default: "console"

# Health check configuration
health:
  health_check_interval: "5s"   # Frequency of service health checks
                                # Format: Go duration string (e.g., "5s", "1m")
                                # Service checks: Database connectivity
                                # Default: "5s"

# Auth service connection (for token verification)
auth:
  host: "localhost"           # Host address of the auth service
                              # Default: "localhost"
  port: 50051                 # Port of the auth service
                              # Default: 50051