apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  DB_HOST: "host.minikube.internal"     # Special DNS name to reach host machine
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"  # In production, use secrets!
  DB_NAME: "auth_db"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "50051"
  GRAPH_HOST: "graph-service"  # Service name of graph service
  GRAPH_PORT: "50052"