apiVersion: v1
kind: Service
metadata:
  name: auth-service  # Name of the service
spec:
  selector:
    app: auth-service  # Select pods with this label
  ports:
  - name: grpc        # Name of the port
    port: 50051       # Port the service listens on
    targetPort: 50051 # Port to forward to in the pod
    nodePort: 30051   # Specific external port on the node
  type: NodePort     # Allow external access