apiVersion: v1
kind: Service
metadata:
  name: graph-service  # Name of the service
spec:
  selector:
    app: graph-service  # Select pods with this label
  ports:
  - name: grpc        # Name of the port
    port: 50052       # Port the service listens on
    targetPort: 50052 # Port to forward to in the pod
    nodePort: 30052   # Specific external port on the node
  type: NodePort     # Allow external access