name: Build and Push Docker images

on:
  push:
    branches: [ "main" ]  # or your default branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push auth service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.auth
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

      - name: Build and push graph service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.graph
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/graph-service:latest